package com.community.tools.util.statemachie;


public enum State {
  NEW_USER, FIRST_LICENSE_MESS, SECOND_LICENSE_MESS, AGREED_LICENSE, ADDED_GIT, GOT_THE_FIRST_TASK,
  CHECK_FOR_NEW_TASK, CONGRATS_LAST_TASK
}
