package com.community.tools.util.statemachie;


public enum State {
  NEW_USER, AGREED_LICENSE, ADDED_GIT, GOT_THE_NEXT_TASK, CHECK_FOR_NEW_TASK,
  CONGRATS_LAST_TASK, CHECK_LOGIN, FIRST_QUESTION, SECOND_QUESTION, THIRD_QUESTION,
  ESTIMATE_THE_TASK
}
